/**
 * Diablo Immortal PWA Service Worker
 * Auto-generated by update-service-worker.js
 */

const CACHE_NAME = 'monk-journey-cache';
const CACHE_VERSION = '12';
const CACHE_KEY = CACHE_NAME + '-v' + CACHE_VERSION;

// Total cache size in bytes and MB
const TOTAL_CACHE_SIZE_BYTES = 5628033;
const TOTAL_CACHE_SIZE_MB = 5.37;

// Assets to cache
const ASSETS_TO_CACHE = [
  '',
  'manifest.json',
  'css/animations.css',
  'css/dialog.css',
  'css/game-menu.css',
  'css/game.css',
  'css/hud-manager.css',
  'css/icons.css',
  'css/initial-loading.css',
  'css/inventory.css',
  'css/loading-screen.css',
  'css/main.css',
  'css/notifications.css',
  'css/orientation-message.css',
  'css/performance-manager.css',
  'css/reset.css',
  'css/settings-menu.css',
  'css/skill-preview.css',
  'css/skill-selection.css',
  'css/skill-tree.css',
  'css/utilities.css',
  'css/variables.css',
  'js/AudioManager.js',
  'js/CollisionManager.js',
  'js/DifficultyManager.js',
  'js/EffectsManager.js',
  'js/InputHandler.js',
  'js/PerformanceManager.js',
  'js/QuestManager.js',
  'js/UIComponent.js',
  'js/config/colors.js',
  'js/config/drops.js',
  'js/config/enemies.js',
  'js/config/enemy-behavior.js',
  'js/config/environment.js',
  'js/config/input.js',
  'js/config/player-models.js',
  'js/config/quality-levels.js',
  'js/config/render.js',
  'js/config/skill-icons.js',
  'js/config/skill-preview.js',
  'js/config/skill-tree.js',
  'js/config/skills.js',
  'js/config/sounds.js',
  'js/config/storage-keys.js',
  'js/config/structure.js',
  'js/config/terrain.js',
  'js/effects/EffectObjectPool.js',
  'js/entities/enemies/Enemy.js',
  'js/entities/enemies/EnemyManager.js',
  'js/entities/enemies/models/CorruptedTreantModel.js',
  'js/entities/enemies/models/DefaultModel.js',
  'js/entities/enemies/models/DemonModel.js',
  'js/entities/enemies/models/EnemyModel.js',
  'js/entities/enemies/models/EnemyModelFactory.js',
  'js/entities/enemies/models/FireElementalModel.js',
  'js/entities/enemies/models/FrostElementalModel.js',
  'js/entities/enemies/models/FrostTitanModel.js',
  'js/entities/enemies/models/InfernalGolemModel.js',
  'js/entities/enemies/models/MountainTrollModel.js',
  'js/entities/enemies/models/NecromancerModel.js',
  'js/entities/enemies/models/ShadowBeastModel.js',
  'js/entities/enemies/models/SimpleEnemyModel.js',
  'js/entities/enemies/models/SkeletonArcherModel.js',
  'js/entities/enemies/models/SkeletonModel.js',
  'js/entities/enemies/models/SwampWitchModel.js',
  'js/entities/enemies/models/VoidWraithModel.js',
  'js/entities/enemies/models/ZombieBruteModel.js',
  'js/entities/enemies/models/ZombieModel.js',
  'js/entities/player/FallbackPlayerModel.js',
  'js/entities/player/Player.js',
  'js/entities/player/PlayerCombat.js',
  'js/entities/player/PlayerInterface.js',
  'js/entities/player/PlayerInventory.js',
  'js/entities/player/PlayerModel.js',
  'js/entities/player/PlayerMovement.js',
  'js/entities/player/PlayerSkills.js',
  'js/entities/player/PlayerState.js',
  'js/entities/player/PlayerStats.js',
  'js/entities/skills/BleedingEffect.js',
  'js/entities/skills/BreathOfHeavenEffect.js',
  'js/entities/skills/CycloneStrikeEffect.js',
  'js/entities/skills/DeadlyReachEffect.js',
  'js/entities/skills/ExplodingPalmEffect.js',
  'js/entities/skills/FistOfThunderEffect.js',
  'js/entities/skills/FlyingDragonEffect.js',
  'js/entities/skills/FlyingKickEffect.js',
  'js/entities/skills/ImprisonedFistsEffect.js',
  'js/entities/skills/InnerSanctuaryEffect.js',
  'js/entities/skills/MysticAllyEffect.js',
  'js/entities/skills/SevenSidedStrikeEffect.js',
  'js/entities/skills/ShieldOfZenEffect.js',
  'js/entities/skills/Skill.js',
  'js/entities/skills/SkillEffect.js',
  'js/entities/skills/SkillEffectFactory.js',
  'js/entities/skills/TeleportSkillEffect.js',
  'js/entities/skills/WaveOfLightEffect.js',
  'js/entities/skills/WaveStrikeEffect.js',
  'js/entities/utils/CharacterModelPool.js',
  'js/entities/utils/EnemyObjectPool.js',
  'js/game/Game.js',
  'js/game/GameEvents.js',
  'js/game/GameState.js',
  'js/game/LoadingManager.js',
  'js/game/SceneOptimizer.js',
  'js/hud-manager/DeathScreenUI.js',
  'js/hud-manager/DialogUI.js',
  'js/hud-manager/EnemyUI.js',
  'js/hud-manager/HUDManager.js',
  'js/hud-manager/HomeUI.js',
  'js/hud-manager/InventoryButton.js',
  'js/hud-manager/InventoryUI.js',
  'js/hud-manager/MiniMapButton.js',
  'js/hud-manager/MiniMapUI.js',
  'js/hud-manager/NotificationsUI.js',
  'js/hud-manager/PlayerUI.js',
  'js/hud-manager/QuestLogUI.js',
  'js/hud-manager/SkillSelectionButton.js',
  'js/hud-manager/SkillSelectionUI.js',
  'js/hud-manager/SkillTreeButton.js',
  'js/hud-manager/SkillTreeUI.js',
  'js/hud-manager/SkillsUI.js',
  'js/hud-manager/VirtualJoystickUI.js',
  'js/menu-system/ControlsDisplay.js',
  'js/menu-system/EnemyPreview.js',
  'js/menu-system/GameMenu.js',
  'js/menu-system/IMenu.js',
  'js/menu-system/MainBackground.js',
  'js/menu-system/MenuManager.js',
  'js/menu-system/ModelPreview.js',
  'js/menu-system/SettingsMenu.js',
  'js/menu-system/SkillPreview.js',
  'js/save-manager/ISaveSystem.js',
  'js/save-manager/IStorageAdapter.js',
  'js/save-manager/LocalStorageAdapter.js',
  'js/save-manager/SaveManager.js',
  'js/save-manager/serializers/PlayerSerializer.js',
  'js/save-manager/serializers/QuestSerializer.js',
  'js/save-manager/serializers/SettingsSerializer.js',
  'js/save-manager/utils/SaveOperationProgress.js',
  'js/save-manager/utils/SaveUtils.js',
  'js/services/InteractionResultHandler.js',
  'js/types.js',
  'js/utils/AnimationUtils.js',
  'js/utils/SkillTreeUtils.js',
  'js/world/WorldManager.js',
  'js/world/environment/Bush.js',
  'js/world/environment/EnvironmentManager.js',
  'js/world/environment/Flower.js',
  'js/world/environment/FogManager.js',
  'js/world/environment/Rock.js',
  'js/world/environment/Tree.js',
  'js/world/interactive/BossSpawnPoint.js',
  'js/world/interactive/InteractiveObjectManager.js',
  'js/world/interactive/QuestMarker.js',
  'js/world/interactive/TreasureChest.js',
  'js/world/lighting/LightingManager.js',
  'js/world/structures/Bridge.js',
  'js/world/structures/Building.js',
  'js/world/structures/DarkSanctum.js',
  'js/world/structures/Mountain.js',
  'js/world/structures/Ruins.js',
  'js/world/structures/StructureManager.js',
  'js/world/structures/Tower.js',
  'js/world/structures/Village.js',
  'js/world/terrain/TerrainManager.js',
  'js/world/utils/EnvironmentObjectPool.js',
  'js/world/utils/ModelObjectPool.js',
  'js/world/utils/ObjectPool.js',
  'js/world/utils/RandomGenerator.js',
  'js/world/utils/TerrainChunkPool.js',
  'js/world/utils/TextureGenerator.js',
  'js/world/zones/ZoneManager.js',
  'images/home.jpg',
  'images/logo-192.png',
  'images/logo-192.svg',
  'images/logo-512.png',
  'images/logo-512.svg',
  'assets/audio/ally_dismiss.mp3',
  'assets/audio/ally_summon.mp3',
  'assets/audio/attack.mp3',
  'assets/audio/barrier_dissipate.mp3',
  'assets/audio/barrier_form.mp3',
  'assets/audio/battle_theme.mp3',
  'assets/audio/bell_fade.mp3',
  'assets/audio/bell_ring.mp3',
  'assets/audio/boss_death.mp3',
  'assets/audio/boss_theme.mp3',
  'assets/audio/button_click.mp3',
  'assets/audio/chest_open.mp3',
  'assets/audio/cyclone_strike.mp3',
  'assets/audio/door_open.mp3',
  'assets/audio/enemy_attack.mp3',
  'assets/audio/enemy_death.mp3',
  'assets/audio/enemy_hit.mp3',
  'assets/audio/exploding_palm.mp3',
  'assets/audio/fist_of_thunder.mp3',
  'assets/audio/inner_sanctuary.mp3',
  'assets/audio/inventory_open.mp3',
  'assets/audio/item_pickup.mp3',
  'assets/audio/level_up.mp3',
  'assets/audio/main_theme.mp3',
  'assets/audio/mark_applied.mp3',
  'assets/audio/massive_explosion.mp3',
  'assets/audio/mystic_ally.mp3',
  'assets/audio/player_death.mp3',
  'assets/audio/player_hit.mp3',
  'assets/audio/rapid_strike.mp3',
  'assets/audio/seven_sided_strike.mp3',
  'assets/audio/strike_complete.mp3',
  'assets/audio/thunder_echo.mp3',
  'assets/audio/thunder_strike.mp3',
  'assets/audio/water_dissipate.mp3',
  'assets/audio/water_impact.mp3',
  'assets/audio/wave_of_light.mp3',
  'assets/audio/wave_strike.mp3',
  'assets/audio/wind_dissipate.mp3',
  'assets/audio/wind_pull.mp3',
  'assets/effects/buddha.glb',
  'assets/images/background.jpg',
  'assets/models/monk-v3.glb',
  'assets/models/monk.glb'
];

// File sizes in bytes for progress reporting
const FILE_SIZES =   {
    "": 29452,
    "manifest.json": 571,
    "css/animations.css": 916,
    "css/dialog.css": 529,
    "css/game-menu.css": 7172,
    "css/game.css": 265,
    "css/hud-manager.css": 13136,
    "css/initial-loading.css": 873,
    "css/loading-screen.css": 522,
    "css/main.css": 1152,
    "css/notifications.css": 2290,
    "css/orientation-message.css": 422,
    "css/performance-manager.css": 1112,
    "css/reset.css": 1275,
    "css/settings-menu.css": 18790,
    "css/skill-icons.css": 5839,
    "css/skill-preview.css": 1298,
    "css/skill-selection.css": 7967,
    "css/skill-tree.css": 7127,
    "css/utilities.css": 2433,
    "js/AudioManager.js": 22440,
    "js/CollisionManager.js": 12859,
    "js/DifficultyManager.js": 4858,
    "js/EffectsManager.js": 5211,
    "js/InputHandler.js": 19068,
    "js/Main.js": 4310,
    "js/PerformanceManager.js": 31359,
    "js/QuestManager.js": 18462,
    "js/UIComponent.js": 2612,
    "js/config/colors.js": 6405,
    "js/config/drops.js": 2016,
    "js/config/enemies.js": 18071,
    "js/config/enemy-behavior.js": 1452,
    "js/config/environment.js": 430,
    "js/config/input.js": 2147,
    "js/config/player-models.js": 1619,
    "js/config/quality-levels.js": 1318,
    "js/config/render.js": 4327,
    "js/config/skill-icons.js": 20043,
    "js/config/skill-preview.js": 585,
    "js/config/skill-tree.js": 32041,
    "js/config/skills.js": 10852,
    "js/config/sounds.js": 13857,
    "js/config/storage-keys.js": 1060,
    "js/config/structure.js": 817,
    "js/config/terrain.js": 497,
    "js/effects/EffectObjectPool.js": 25995,
    "js/entities/Enemy.js": 20221,
    "js/entities/EnemyManager.js": 27012,
    "js/entities/models/DefaultModel.js": 2242,
    "js/entities/models/DemonModel.js": 5915,
    "js/entities/models/EnemyModel.js": 1656,
    "js/entities/models/EnemyModelFactory.js": 2587,
    "js/entities/models/FrostTitanModel.js": 7186,
    "js/entities/models/InfernalGolemModel.js": 4976,
    "js/entities/models/NecromancerModel.js": 4322,
    "js/entities/models/ShadowBeastModel.js": 3457,
    "js/entities/models/SkeletonModel.js": 3431,
    "js/entities/models/ZombieModel.js": 3195,
    "js/entities/player/FallbackPlayerModel.js": 5656,
    "js/entities/player/Player.js": 7681,
    "js/entities/player/PlayerCombat.js": 14394,
    "js/entities/player/PlayerInterface.js": 4557,
    "js/entities/player/PlayerInventory.js": 2993,
    "js/entities/player/PlayerModel.js": 55435,
    "js/entities/player/PlayerMovement.js": 8229,
    "js/entities/player/PlayerSkills.js": 19162,
    "js/entities/player/PlayerState.js": 1428,
    "js/entities/player/PlayerStats.js": 7212,
    "js/entities/skills/BleedingEffect.js": 11860,
    "js/entities/skills/BreathOfHeavenEffect.js": 10751,
    "js/entities/skills/CycloneStrikeEffect.js": 14218,
    "js/entities/skills/DeadlyReachEffect.js": 14204,
    "js/entities/skills/ExplodingPalmEffect.js": 26267,
    "js/entities/skills/FistOfThunderEffect.js": 14665,
    "js/entities/skills/FlyingDragonEffect.js": 13620,
    "js/entities/skills/FlyingKickEffect.js": 10143,
    "js/entities/skills/InnerSanctuaryEffect.js": 18464,
    "js/entities/skills/MysticAllyEffect.js": 25597,
    "js/entities/skills/SevenSidedStrikeEffect.js": 19501,
    "js/entities/skills/ShieldOfZenEffect.js": 18236,
    "js/entities/skills/Skill.js": 9340,
    "js/entities/skills/SkillEffect.js": 3871,
    "js/entities/skills/SkillEffectFactory.js": 5303,
    "js/entities/skills/TeleportSkillEffect.js": 14179,
    "js/entities/skills/WaveOfLightEffect.js": 21308,
    "js/entities/skills/WaveStrikeEffect.js": 13273,
    "js/entities/utils/CharacterModelPool.js": 6803,
    "js/entities/utils/EnemyObjectPool.js": 6592,
    "js/game/Game.js": 21416,
    "js/game/GameEvents.js": 1148,
    "js/game/GameState.js": 1314,
    "js/game/LoadingManager.js": 1599,
    "js/game/SceneOptimizer.js": 4564,
    "js/hud-manager/DeathScreenUI.js": 1852,
    "js/hud-manager/DialogUI.js": 1843,
    "js/hud-manager/EnemyUI.js": 1842,
    "js/hud-manager/HUDManager.js": 12047,
    "js/hud-manager/HomeUI.js": 4112,
    "js/hud-manager/InventoryUI.js": 4627,
    "js/hud-manager/MiniMapUI.js": 29954,
    "js/hud-manager/NotificationsUI.js": 18719,
    "js/hud-manager/PlayerUI.js": 3867,
    "js/hud-manager/QuestLogUI.js": 2709,
    "js/hud-manager/SkillSelectionButton.js": 4378,
    "js/hud-manager/SkillSelectionUI.js": 31145,
    "js/hud-manager/SkillTreeUI.js": 13940,
    "js/hud-manager/SkillsUI.js": 5889,
    "js/hud-manager/VirtualJoystickUI.js": 6986,
    "js/menu-system/EnemyPreview.js": 14490,
    "js/menu-system/GameMenu.js": 10157,
    "js/menu-system/IMenu.js": 836,
    "js/menu-system/MainBackground.js": 2851,
    "js/menu-system/MenuManager.js": 5424,
    "js/menu-system/ModelPreview.js": 16289,
    "js/menu-system/ReloadUI.js": 3308,
    "js/menu-system/SettingsMenu.js": 54178,
    "js/menu-system/SkillPreview.js": 27377,
    "js/save-manager/ISaveSystem.js": 1255,
    "js/save-manager/IStorageAdapter.js": 1060,
    "js/save-manager/LocalStorageAdapter.js": 1831,
    "js/save-manager/SaveManager.js": 18437,
    "js/save-manager/serializers/PlayerSerializer.js": 4913,
    "js/save-manager/serializers/QuestSerializer.js": 3791,
    "js/save-manager/serializers/SettingsSerializer.js": 3440,
    "js/save-manager/utils/SaveOperationProgress.js": 6226,
    "js/save-manager/utils/SaveUtils.js": 2288,
    "js/types.js": 8275,
    "js/utils/AnimationUtils.js": 10583,
    "js/utils/SkillTreeUtils.js": 3141,
    "js/world/WorldManager.js": 23887,
    "js/world/environment/Bush.js": 1849,
    "js/world/environment/EnvironmentManager.js": 21038,
    "js/world/environment/Flower.js": 4019,
    "js/world/environment/FogManager.js": 11408,
    "js/world/environment/Rock.js": 4594,
    "js/world/environment/Tree.js": 4528,
    "js/world/interactive/BossSpawnPoint.js": 1470,
    "js/world/interactive/InteractiveObjectManager.js": 14245,
    "js/world/interactive/QuestMarker.js": 8874,
    "js/world/interactive/TreasureChest.js": 6117,
    "js/world/lighting/LightingManager.js": 6719,
    "js/world/structures/Bridge.js": 14934,
    "js/world/structures/Building.js": 15301,
    "js/world/structures/DarkSanctum.js": 5009,
    "js/world/structures/Mountain.js": 14043,
    "js/world/structures/Ruins.js": 5086,
    "js/world/structures/StructureManager.js": 26102,
    "js/world/structures/Tower.js": 16012,
    "js/world/structures/Village.js": 21869,
    "js/world/terrain/TerrainManager.js": 48019,
    "js/world/utils/EnvironmentObjectPool.js": 6903,
    "js/world/utils/ModelObjectPool.js": 4476,
    "js/world/utils/ObjectPool.js": 6825,
    "js/world/utils/RandomGenerator.js": 2214,
    "js/world/utils/TerrainChunkPool.js": 4878,
    "js/world/utils/TextureGenerator.js": 4292,
    "js/world/zones/ZoneManager.js": 13789,
    "images/home.jpg": 141566,
    "images/logo-192.png": 15541,
    "images/logo-192.svg": 345,
    "images/logo-512.png": 62939,
    "images/logo-512.svg": 347,
    "assets/audio/ally_dismiss.mp3": 3456,
    "assets/audio/ally_summon.mp3": 2688,
    "assets/audio/attack.mp3": 2688,
    "assets/audio/barrier_dissipate.mp3": 4224,
    "assets/audio/barrier_form.mp3": 3456,
    "assets/audio/battle_theme.mp3": 40320,
    "assets/audio/bell_fade.mp3": 4224,
    "assets/audio/bell_ring.mp3": 5952,
    "assets/audio/boss_death.mp3": 5952,
    "assets/audio/boss_theme.mp3": 40320,
    "assets/audio/button_click.mp3": 1152,
    "assets/audio/chest_open.mp3": 2688,
    "assets/audio/cyclone_strike.mp3": 3456,
    "assets/audio/door_open.mp3": 3456,
    "assets/audio/enemy_attack.mp3": 1920,
    "assets/audio/enemy_death.mp3": 3456,
    "assets/audio/enemy_hit.mp3": 1152,
    "assets/audio/exploding_palm.mp3": 3456,
    "assets/audio/fist_of_thunder.mp3": 2688,
    "assets/audio/inner_sanctuary.mp3": 4992,
    "assets/audio/inventory_open.mp3": 1920,
    "assets/audio/item_pickup.mp3": 1920,
    "assets/audio/level_up.mp3": 3456,
    "assets/audio/main_theme.mp3": 585978,
    "assets/audio/mark_applied.mp3": 2688,
    "assets/audio/massive_explosion.mp3": 4992,
    "assets/audio/mystic_ally.mp3": 4224,
    "assets/audio/player_death.mp3": 4224,
    "assets/audio/player_hit.mp3": 1920,
    "assets/audio/rapid_strike.mp3": 1920,
    "assets/audio/seven_sided_strike.mp3": 4224,
    "assets/audio/strike_complete.mp3": 2688,
    "assets/audio/thunder_echo.mp3": 3456,
    "assets/audio/thunder_strike.mp3": 1920,
    "assets/audio/water_dissipate.mp3": 3456,
    "assets/audio/water_impact.mp3": 1920,
    "assets/audio/wave_of_light.mp3": 4992,
    "assets/audio/wave_strike.mp3": 2688,
    "assets/audio/wind_dissipate.mp3": 3456,
    "assets/audio/wind_pull.mp3": 2688,
    "assets/effects/buddha.glb": 1902480,
    "assets/images/background.jpg": 465241,
    "assets/models/monk-v3.glb": 155292,
    "assets/models/monk.glb": 366580
  };

// Function to send progress updates to the client
function sendProgressUpdate(completed, total, currentFile, loadedBytes, totalBytes) {
  if (messagePort) {
    messagePort.postMessage({
      type: 'CACHE_PROGRESS',
      completed,
      total,
      currentFile,
      loadedBytes,
      totalBytes,
      totalSizeMB: TOTAL_CACHE_SIZE_MB
    });
  }
}

// Communication channel
let messagePort = null;

// Listen for messages from the client
self.addEventListener('message', event => {
  // Check if it's the initialization message with the port
  if (event.data && event.data.type === 'INIT_PORT') {
    messagePort = event.data.port;
    console.debug('Communication channel established with client');
  }
});

// Function to cache files with progress tracking
async function cacheFilesWithProgress(cache) {
  const total = ASSETS_TO_CACHE.length;
  let completed = 0;
  let loadedBytes = 0;
  
  // Process files sequentially to ensure accurate progress tracking
  for (const url of ASSETS_TO_CACHE) {
    try {
      // Get file size (or 0 if not available)
      const fileSize = FILE_SIZES[url] || 0;
      
      // Send progress update before starting the fetch
      sendProgressUpdate(completed, total, url, loadedBytes, TOTAL_CACHE_SIZE_BYTES);
      
      // Fetch and cache the file
      const response = await fetch(url);
      if (response.ok) {
        await cache.put(url, response);
        completed++;
        loadedBytes += fileSize;
        
        // Send progress update after successful caching
        sendProgressUpdate(completed, total, url, loadedBytes, TOTAL_CACHE_SIZE_BYTES);
      } else {
        console.warn(`Failed to cache ${url}: ${response.status} ${response.statusText}`);
        // Still increment completed to keep progress moving
        completed++;
        sendProgressUpdate(completed, total, `Failed: ${url}`, loadedBytes, TOTAL_CACHE_SIZE_BYTES);
      }
    } catch (error) {
      console.error(`Error caching ${url}:`, error);
      // Still increment completed to keep progress moving
      completed++;
      sendProgressUpdate(completed, total, `Error: ${url}`, loadedBytes, TOTAL_CACHE_SIZE_BYTES);
    }
  }
  
  return completed;
}

// Install event - cache all static assets with progress tracking
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_KEY)
      .then(cache => {
        console.debug('Caching app assets with progress tracking');
        console.debug(`Total cache size: ${TOTAL_CACHE_SIZE_MB} MB with progress tracking`);
        return cacheFilesWithProgress(cache);
      })
      .then(completedCount => {
        console.debug(`Cached ${completedCount} files successfully`);
        return self.skipWaiting();
      })
      .catch(error => {
        console.error('Failed to cache assets:', error);
      })
  );
});

// Activate event - clean up old caches
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.filter(cacheName => {
          return cacheName.startsWith(CACHE_NAME) && cacheName !== CACHE_KEY;
        }).map(cacheName => {
          console.debug('Deleting old cache:', cacheName);
          return caches.delete(cacheName);
        })
      );
    }).then(() => {
      return self.clients.claim();
    })
  );
});

// Fetch event - serve from cache, fall back to network
self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request)
      .then(response => {
        if (response) {
          return response;
        }
        return fetch(event.request);
      })
      .catch(error => {
        console.error('Fetch error:', error);
        // You could return a custom offline page here
      })
  );
});
